### ISSUE TITLE
项目部署报错，怎么解决？

### ISSUE THREAD

**Issue by DOnlyone** [renrenio/renren-security#27]
The type org.quartz.Scheduler cannot be resolved. It is indirectly referenced from required .class files	ScheduleJobServiceImpl.java	/renren-security/renren-admin/src/main/java/io/renren/modules/job/service/impl	line 1	Java Problem

**Comment by sunlightcs** [comment]
没看出什么问题

**Comment by DOnlyone** [comment]
已解决，感谢
